from __future__ import annotations


def _render_idea_block(fields: dict[str, str]) -> str:
    return "\n".join(
        [
            f"## Idea: {fields['title']}",
            "",
            "## Metadata",
            "",
            f"- Idea ID: `{fields['idea_id']}`",
            f"- Codename (kebab case): {fields['codename']}",
            f"- Title: {fields['title']}",
            f"- Date: {fields['date']}",
            f"- Owner: {fields['owner']}",
            f"- Status: {fields['status']}",
            f"- Sensitivity: {fields['sensitivity']}",
            "",
            "## Problem Definition",
            "",
            f"- Problem statement: {fields['problem_statement']}",
            f"- Affected users/personas: {fields['affected_users']}",
            f"- Why now: {fields['why_now']}",
            f"- Current alternatives: {fields['current_alternatives']}",
            "",
            "## Hypotheses",
            "",
            f"- Value hypothesis: {fields['value_hypothesis']}",
            f"- Adoption hypothesis: {fields['adoption_hypothesis']}",
            f"- Feasibility hypothesis: {fields['feasibility_hypothesis']}",
            "",
            "## Proposed Scope",
            "",
            f"- MVP scope: {fields['mvp_scope']}",
            f"- Out of scope: {fields['out_of_scope']}",
            f"- Assumptions: {fields['assumptions']}",
            f"- Constraints: {fields['constraints']}",
            "",
            "## Governance Rationale",
            "",
            f"- Why this idea should be pursued: {fields['why_pursue']}",
            f"- Strategic alignment: {fields['strategic_alignment']}",
            f"- Non-goals: {fields['non_goals']}",
            "",
            "## Risks and Unknowns",
            "",
            f"- Top risks (link to risk entries): {fields['top_risks']}",
            f"- Open questions: {fields['open_questions']}",
            f"- Dependency concerns: {fields['dependency_concerns']}",
            "",
            "## Decisions and ADR Links",
            "",
            f"- Related decisions: {fields['related_decisions']}",
            f"- Related ADRs (`docs/adr/ADR-XXXX-*.md`): {fields['related_adrs']}",
            "",
            "## Validation Plan",
            "",
            f"- Evidence needed: {fields['evidence_needed']}",
            f"- Test plan: {fields['test_plan']}",
            f"- Success criteria: {fields['success_criteria']}",
            f"- Failure criteria: {fields['failure_criteria']}",
            "",
            "## Review and Export Readiness",
            "",
            f"- Latest review outcome: {fields['latest_review_outcome']}",
            f"- Conditions to finalize: {fields['conditions_to_finalize']}",
            f"- Optional summary export path: {fields['summary_export']}",
            "",
            "## Traceability",
            "",
            f"- Session links: {fields['session_links']}",
            "- Catalog reference: `IDEA_CATALOG.md`",
        ]
    )
