from __future__ import annotations

from template_cli.finalize_helpers import STATE_SCHEMA_VERSION

STATE_DEFAULTS = {
    "schemaVersion": STATE_SCHEMA_VERSION,
    "status": "draft",
    "finalizedAt": "",
    "ideaId": "",
    "projectName": "",
    "owner": "",
    "purpose": "",
    "projectType": "",
    "techStack": {"language": "", "runtime": "", "framework": "", "packageTool": ""},
    "persistence": "",
    "authentication": "",
    "determinism": "",
    "packaging": "",
    "constraints": "",
    "commands": {"build": "", "run": "", "test": ""},
    "product": {
        "problemStatement": "",
        "targetUsers": "",
        "whyNow": "",
        "expectedValue": "",
        "solutionSummary": "",
        "mvpScope": "",
        "outOfScope": "",
        "assumptions": "",
        "nonGoals": "",
    },
    "governance": {
        "keyDecisions": "",
        "topRisks": "",
        "mitigationPlans": "",
        "contingencies": "",
        "remainingAcceptedRisks": "",
        "latestReviewOutcome": "",
        "latestReviewSession": "",
    },
    "artifacts": {
        "ideaFiles": [],
        "sessionFiles": [],
        "noteReferences": "",
        "summaryExport": "",
        "finalizationSession": "",
        "adrReferences": [],
    },
}
SCALAR_LABELS = {
    "purpose": [
        "One-sentence objective",
        "Problem statement",
        "Value hypothesis",
        "Summary rationale",
        "Situation summary",
    ],
    "projectType": ["Project type"],
    "techStack.language": ["Language"],
    "techStack.runtime": ["Runtime"],
    "techStack.framework": ["Framework"],
    "techStack.packageTool": ["Package manager/build tool", "Package tool", "Build tool"],
    "persistence": ["Persistence"],
    "authentication": ["Authentication"],
    "determinism": ["Determinism/correctness sensitivity", "Determinism"],
    "packaging": ["Packaging/distribution planned", "Packaging"],
    "constraints": ["Constraints"],
    "commands.build": ["Build command"],
    "commands.run": ["Run command"],
    "commands.test": ["Test command"],
    "product.problemStatement": ["Problem statement"],
    "product.targetUsers": ["Affected users/personas", "Target users"],
    "product.whyNow": ["Why now"],
    "product.expectedValue": ["Expected value", "Value hypothesis"],
    "product.solutionSummary": ["Solution summary", "Value hypothesis"],
    "product.mvpScope": ["MVP scope"],
    "product.outOfScope": ["Out of scope"],
    "product.assumptions": ["Assumptions"],
    "product.nonGoals": ["Non-goals"],
    "governance.keyDecisions": ["Key decisions", "Chosen option"],
    "governance.topRisks": ["Top risks", "Top risks (link to risk entries)", "Risk statement"],
    "governance.mitigationPlans": ["Mitigation plans", "Preventive mitigation"],
    "governance.contingencies": ["Contingency plan"],
    "governance.remainingAcceptedRisks": ["Remaining accepted risks"],
    "governance.latestReviewOutcome": ["Latest review outcome", "Result"],
}
CONTRACT_KEY_BY_TITLE = {
    "Workspace / Package Layout": "workspaceLayout",
    "Storage Implementation": "storageImplementation",
    "CLI Command Surface": "cliCommandSurface",
    "Domain Statuses And Rules": "domainRules",
    "Schedule / Event Semantics": "scheduleEventSemantics",
    "MVP Exclusions": "mvpExclusions",
    "Test Baseline": "testBaseline",
    "Post-MVP Decisions": "postMvpDecisions",
}
REQUIRED_PATHS = [
    "purpose",
    "projectType",
    "techStack.language",
    "techStack.runtime",
    "commands.build",
    "commands.run",
    "commands.test",
    "product.problemStatement",
    "product.mvpScope",
]
EMPTY_HANDOFF_VALUES = {"", "_none_", "_n/a_", "_none yet_", "pass | conditional-pass | fail"}
