from __future__ import annotations

from template_cli.validator_plugins import PLUGIN_MANIFEST, PLUGIN_MARKETPLACE, PLUGIN_SKILL_ARTIFACTS
from template_cli.validator_skills import REPO_SKILLS, REPO_SKILL_METADATA


REPO_SKILL_ARTIFACTS = [
    artifact
    for skill_path, metadata_path in zip(REPO_SKILLS.values(), REPO_SKILL_METADATA.values())
    for artifact in (skill_path, metadata_path)
]
REPO_PLUGIN_ARTIFACTS = [PLUGIN_MARKETPLACE, PLUGIN_MANIFEST, *PLUGIN_SKILL_ARTIFACTS]

BRAINSTORMING_CORE_ARTIFACTS = [
    ".editorconfig",
    ".gitattributes",
    ".gitignore",
    "LICENSE",
    "README.md",
    "BOOTSTRAP_TOOL.md",
    "HARNESS_IMPROVEMENT_ROADMAP.md",
    "AGENTS.md",
    "MODE.md",
    *REPO_SKILL_ARTIFACTS,
    *REPO_PLUGIN_ARTIFACTS,
    "harness_commands/CONVERSATIONAL_MODE.md",
    "harness_commands/COMMANDS.md",
    "harness_commands/intent_registry.json",
    "brainstorming/AGENTS.brainstorming.md",
    "brainstorming/QUICKSTART.md",
    "brainstorming/EXAMPLE_LIFECYCLE.md",
    "brainstorming/FILE_MAP.md",
    "IDEA_CATALOG.md",
    "NOTES_CATALOG.md",
    "ideas/_inbox.md",
    "ideas/_active.md",
    "ideas/_parked.md",
    "ideas/_killed.md",
    "sessions/",
    "notes/",
    "exports/",
    "brainstorming/templates/idea_template.md",
    "brainstorming/templates/decision_template.md",
    "brainstorming/templates/note_template.md",
    "brainstorming/templates/project_plan_packet_template.md",
    "brainstorming/templates/risk_template.md",
    "brainstorming/templates/review_gate_template.md",
    "brainstorming/docs/adr/template.md",
    "brainstorming/docs/adr/ADR-0001-adopt-governance-structure-for-idea-lab.md",
    "scripts/lab",
    "scripts/lab.sh",
    "scripts/lab.ps1",
    "scripts/validate-brainstorming.ps1",
    "scripts/validate-governance.ps1",
    "scripts/lab-sync.ps1",
    "scripts/lab-note.ps1",
    "scripts/project-harness.ps1",
    "scripts/sync-plugin-skills.ps1",
    "scripts/finalize-project.sh",
    "scripts/render-development-docs.sh",
    "scripts/sync-plugin-skills.sh",
    "scripts/validate-development.sh",
    "scripts/validate-brainstorming.sh",
    "scripts/validate-governance.sh",
    "scripts/lab-sync.sh",
    "scripts/lab-note.sh",
    "scripts/project-harness.sh",
    "scripts/finalize-project",
    "scripts/render-intent-docs",
    "scripts/render-intent-docs.sh",
    "scripts/render-intent-docs.ps1",
    "scripts/sync-plugin-skills",
    "scripts/render-development-docs",
    "scripts/validate-development",
    "scripts/validate-brainstorming",
    "scripts/validate-governance",
    "scripts/lab-sync",
    "scripts/lab-note",
    "scripts/project-harness",
    "tests/workflow_test_helpers.py",
    "tests/test_development_rendering.py",
    "tests/test_lab_lifecycle.py",
    "tests/test_lab_launcher.py",
    "tests/test_finalization_regression.py",
    "tests/test_intent_registry_contract.py",
    "tests/test_template_validation.py",
    "tests/test_project_harness_bootstrap.py",
    "tests/fixtures/finalized_state_v2.json",
    "tests/fixtures/finalized_state_web_app_v2.json",
    "tests/fixtures/finalized_state_with_persistence_v2.json",
    "tests/fixtures/finalized_session.md",
    "state/project-init.json",
    ".github/workflows/ci.yml",
    ".github/workflows/governance-audit.yml",
    ".github/PULL_REQUEST_TEMPLATE.md",
    "scripts/python/template_cli/render_governance_templates.py",
    "scripts/python/template_cli/bootstrap.py",
    "scripts/python/template_cli/workflow_render.py",
]

DEVELOPMENT_REQUIRED_ARTIFACTS = [
    ".editorconfig",
    ".gitattributes",
    "LICENSE",
    "AGENTS.md",
    "MODE.md",
    "README.md",
    "CHANGELOG.md",
    ".gitignore",
    *REPO_SKILL_ARTIFACTS,
    *REPO_PLUGIN_ARTIFACTS,
    "NOTES_CATALOG.md",
    "sessions/",
    "notes/",
    "exports/",
    "scripts/lab",
    "scripts/lab.sh",
    "scripts/lab.ps1",
    "scripts/lab-note",
    "scripts/lab-note.sh",
    "scripts/lab-note.ps1",
    "docs/PROJECT_CONTEXT.md",
    "docs/ROADMAP.md",
    "docs/ARCHITECTURE.md",
    "docs/FILE_MAP.md",
    "docs/GOVERNANCE_INDEX.md",
    "docs/VERSIONING_AND_RELEASE_POLICY.md",
    "docs/SECURITY_POLICY.md",
    "docs/RUNTIME_VERIFICATION_REPORT.md",
    "docs/adr/ADR-0001-record-architecture-decisions.md",
    "docs/adr/ADR-TEMPLATE.md",
    "state/project-init.json",
]
